gopasspw/gopassbridge

- web-extension/content.js
Fixes a bug introduced in commit 07eddbf
> Fix clicking the button in tryLogIn

- web-extension/content.js
Which is used by default with keepass2csv2pass.py to import password from keepass2 client.
> Add 'user' in loginInputIds

- tests/unit/content.test.js
#44
The 'ing-nl' case could probably be supported, they are using a `button` element instead of `input`.
I also noticed that jsdom is logging some errors: `Error: Not implemented: HTMLFormElement.prototype.submit`. I'll try to find a way to avoid this.
> #44 Add submit test cases for login pages

- manifests/chrome-manifest-dev.json
- manifests/chrome-manifest.json
- manifests/firefox-manifest.json
- tests/unit/generic.test.js
- web-extension/_locales/de/messages.json
- web-extension/_locales/en/messages.json
- web-extension/generic.js
- web-extension/options.html
> Add ability to trigger notifications.

- README.md
- tests/unit/details.test.js
- tests/unit/gopassbridge.test.js
- tests/unit/popup.test.js
- web-extension/details.js
- web-extension/generic.js
- web-extension/gopassbridge.html
- web-extension/gopassbridge.js
- web-extension/icons/si-glyph-arrow-thick-thin-down.svg
- web-extension/popup.js
- web-extension/search.js
- web-extension/styles.css
- web-extension/vendor/regex-weburl.js
> Detail view implementation

- manifests/chrome-manifest-dev.json
- manifests/chrome-manifest.json
- manifests/firefox-manifest.json
- tests/unit/background.test.js
- web-extension/background.js
- web-extension/content.js
- web-extension/search.js
Initial stab at fixing #20. Thoughts?
> use background process to survive popup auto-closing (#20)

- tests/unit/content.test.js
- web-extension/search.js
Part of #45
- Fix missing "Copied to clipboard" message
- Fix annoying "Not implemented" error during tests
- Start working on search.js
I'll open other PRs for more tests, etc.
> Some search fixes

- web-extension/_locales/de/messages.json
- web-extension/_locales/en/messages.json
- web-extension/options.html
- web-extension/search.js
- web-extension/styles.css
Adds buttons on hover as alternate way to clipboard copy and detail view.
> Morebuttons

- tests/unit/search.test.js
- web-extension/search.js
> [WIP] #45 Improve search state handling and add more tests

- tests/unit/search.test.js
- web-extension/search.js
> Add more search tests

- .gitattributes
- media/GopassBridgeWalkaround.mp4
> Gopassbridge video

- web-extension/_locales/de/messages.json
- web-extension/_locales/en/messages.json
- web-extension/options.html
> Document keyboard shortcut in "Usage Hints"

- web-extension/vendor/browser-polyfill.js
Updates the web extension polyfill. Changes look safe to me.
> update webextension polyfill

- web-extension/create.js
- web-extension/gopassbridge.html
- web-extension/popup.js
- web-extension/styles.css
Add spinner when saving a new secret as this will take some seconds.
> Add feedback when saving a new secret

- CHANGELOG.md
- manifests/chrome-manifest-dev.json
- manifests/chrome-manifest.json
- manifests/firefox-manifest.json
- package.json
- web-extension/_locales/de/messages.json
- web-extension/_locales/en/messages.json
After #99 is merged it might be a good time to release a new version, as plenty of improvements were implemented since the last release.
> Prepare release 0.5.0

- tests/unit/details.test.js
- tests/unit/generic.test.js
- tests/unit/gopassbridge.test.js
- tests/unit/popup.test.js
- web-extension/_locales/de/messages.json
- web-extension/_locales/en/messages.json
- web-extension/details.js
- web-extension/generic.js
- web-extension/gopassbridge.js
- web-extension/popup.js
* Disables sending messages to non http protocol tabs like extensions. The content script is not loading there which causes #93 
* Check for error messages which are symptoms for an incomplete jsonapi setup (missing native messaging manifest). Fixes #97
> Improved error handling and reporting, fixes #97 and #93

- README.md
> Readme: Fix broken link to gopass

- .eslintrc
- .prettierrc
- tests/unit/details.test.js
- web-extension/details.js
> Omit empty values

- tests/unit/create.test.js
- web-extension/_locales/de/messages.json
- web-extension/_locales/en/messages.json
- web-extension/generic.js
- web-extension/gopassbridge.html
- web-extension/options.html
- web-extension/popup.js
Also allow changing that setting. Closes #126
> Set default password length to 24 to match gopass default setting

- web-extension/gopassbridge.html
- web-extension/styles.css
I changed the buttons CSS to make them outlined and on the same row.
It's just an idea but I can also transform the checkboxes into switch buttons.
I hope it helps.
Thanks in advance for your feedback.
> Change buttons CSS style

- web-extension/generic.js
https://github.com/gopasspw/gopass/blob/cd157a0f46dd1cf4179a4d8317d89736a138385c/pkg/otp/otp.go#L31
> Omit "totp" from being displayed by default

- web-extension/popup.js
> Add chrome error message to link for help, closes #139

- Makefile
- yarn.lock
Upgrade dependencies and use locally installed web-ext and prettier in makefile.
> Upgrade dependencies and use local web-ext and prettier

- tests/unit/generic.test.js
- tests/unit/search.test.js
- web-extension/_locales/de/messages.json
- web-extension/_locales/en/messages.json
- web-extension/generic.js
- web-extension/search.js
> Add tooltips to search result buttons

- tests/unit/search.test.js
- web-extension/search.js
Use the api to copy passwords (#49)
> Copy passwords via gopass json api

- .github/workflows/nodejs.yml
- .prettierignore
- .travis.yml
- CHANGELOG.md
- Makefile
- README.md
- jest.config.js
- package.json
- tests/locales.test.js
- yarn.lock
Includes adjustments to run development commands (test, lint, format) on Windows.
> GitHub Actions to replace Travis 

- CHANGELOG.md
- manifests/chrome-manifest-dev.json
- manifests/chrome-manifest.json
- manifests/firefox-manifest.json
- package.json
> Release v0.8.0

- tests/unit/details.test.js
- web-extension/details.js
RELEASE_NOTES=Hide password in detail view when using gopass v1.10
> Hide password in detail view when using gopass v1.10

- REVIEWERS
> Fix version in REVIEWERS

- .github/workflows/nodejs.yml
https://github.com/actions/setup-node#caching-global-packages-data
> Simplify and fix CI caching

- CHANGELOG.md
- RELEASE.md
- SECURITY.md
- manifests/chrome-manifest-dev.json
- manifests/chrome-manifest.json
- manifests/firefox-manifest.json
- package.json
- web-extension/background.js
Known issue: https://github.com/gopasspw/gopassbridge/issues/263
> Release 2.0.0

- web-extension/styles.css
A small patch to allow for dark/light mode colors based on media-selectors / system preferences.
> Light/Dark mode (based on  media selectors / system prefs)
